### ISSUE TITLE
quip.apps.UrlAuth.prototype.login parameters encoding

### ISSUE THREAD

**Issue by khowling** [quip/quip-apps#10]
Passing in a parameter value to login, that contains a URL, you are encoding the value **twice**! thus cannot be decoded by the IDP.

for example:

.login({"resource": "https://analysis.windows.net/powerbi/api"})
results in : resource=https%253A%252F%252Fanalysis.windows.net%252Fpowerbi%252Fapi
it should be : resource=https%3A%2F%2Fanalysis.windows.net%2Fpowerbi%2Fapi

**Comment by elsigh** [comment]
@yangsu

**Comment by yangsu** [comment]
Thanks for reporting the bug! I will take a look

**Comment by plinehan** [comment]
The fix should go out with today's push.
