### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by ashlynaiu** [quip/quip-apps#11]
I was looking through your documentation (https://salesforce.quip.com/dev/liveapps/#develop) to get started. `npm start` doesn't work and I had to use `npm run dev`. Not sure if its just me, but the documentation might need some updating. 

![screen shot 2018-03-13 at 10 00 43 am](https://user-images.githubusercontent.com/6745427/37357462-bfcb5910-26a5-11e8-86a6-ddf837e75ca3.png)

**Comment by elsigh** [comment]
Can you show me what you have in your `package.json` file?

**Comment by ashlynaiu** [comment]
@elsigh I did some more digging and realized that the Salesforce Trailhead related to Quip Live Apps is outdated. I'll file a bug against their documentation. Thanks for the help.
