### ISSUE TITLE
qla login fails

### ISSUE THREAD

**Issue by Kalvinci** [quip/quip-apps#138]
Unable to login using "qla login".
The following error occurs on visiting the generated URL:
![quip-login-error](https://user-images.githubusercontent.com/23495924/95820961-ae6a3580-0d46-11eb-8885-0c8fc964d289.png)

**Comment by jesseditson** [comment]
The docs on master are a bit ahead of the public release, which is still documented at https://quip.com/dev/liveapps. This is expected for now, but I'll leave this issue open until we release the ability to log in to the public.

**Comment by matteo1123** [comment]
Hello, I am still having issues, the link @jesseditson shared above has instructions on create-quip-app, but it is failing for me, I can't get npm run build to actually export a .ele file.  In my searching I found that npm says create-quip-app is deprecated use  cli instead.  https://www.npmjs.com/package/create-quip-app
but with the cli I get the same page not found discussed above.  

Any ideas would be hugely appreciated.

**Comment by jesseditson** [comment]
Hey - the template create-quip-app generated in an earlier version didn't include `create-quip-app pack`, and apps created with `qla init` don't include that command at all. I posted a fix for older templates here: https://salesforce.stackexchange.com/a/323706/53392

TL:DR; If you used create-quip-app `v0.0.44` or `quip-cli` to generate your app, add `&& create-quip-app pack` to your `npm build` script.

**Comment by matteo1123** [comment]
@jesseditson  I don't want to come across as unprofessional or clog up this discussion, but I do very much want to say. 
![thankyou](https://user-images.githubusercontent.com/51849606/98901366-eb723680-2470-11eb-8d57-56bb27c10022.png)
