### ISSUE TITLE
cannot create live app following instructions

### ISSUE THREAD

**Issue by markwharton** [quip/quip-apps#152]
Kind of [blocked](https://github.com/quip/quip-apps/issues/151) using `quip-cli`, so I decided to try live app instead. Unfortunately, experiencing issues with that too. I followed step-by-step [instructions](https://quip.com/dev/liveapps#create) to create **Hello World** on a Mac v10.14.6, but cannot find any `app.ele ` file to upload.

```
$ node --version
> v10.5.0
$ create-quip-app my-app
```

I have no idea why it creates `live-app` instead of the expected `my-app` directory.
```
$ ls -l1
> live-app
```

I add my app id and update title in manifest.json, and run `npm install` (not listed in the instructions).
```
$ npm run build

> live-app@0.1.0 build /Users/markwharton/Developer/quip/live-app
> NODE_ENV=production webpack

Hash: 743d1253dc19a37b2de7
Version: webpack 4.44.2
Time: 3368ms
Built at: 12/06/2020 5:17:48 PM
 Asset     Size  Chunks             Chunk Names
app.js  154 KiB       0  [emitted]  main
Entrypoint main = app.js
[15] multi ./src/root.tsx 28 bytes {0} [built]
[16] (webpack)/buildin/global.js 472 bytes {0} [built]
[31] ./src/root.tsx + 3 modules 5.71 KiB {0} [built]
     | ./src/root.tsx 597 bytes [built]
     | ./src/menus.ts 2.62 KiB [built]
     | ./src/model/root.ts 609 bytes [built]
     |     + 1 hidden module
    + 29 hidden modules
```

I don't see any errors, but also can't find any `app.ele ` file to upload.
```
$ find . -name *.ele
```

What am I doing wrong?

**Comment by jesseditson** [comment]
Can you try updating to the latest create-quip-app?

`npm i -g create-quip-app`

**Comment by markwharton** [comment]
Thanks Jesse, I tried updating but still seeing the same issue, and version looks the same too.

```
> live-app@0.1.0 build /Users/markwharton/Developer/quip/live-app
> NODE_ENV=production webpack
```

I installed everything fresh on Sunday.

**Comment by jesseditson** [comment]
A few things to try:

- verify that `npm ls -g create-quip-app` shows `create-quip-app@0.1.1`
- run `create-quip-app pack` to verify that it builds an `.ele` file
- check your package.json `build` script, it should contain `create-quip-app pack` after any framework build commands. (see [this answer](https://salesforce.stackexchange.com/a/323706/53392) for context)

**Comment by markwharton** [comment]
OK, seems to work. This is cool. Thank you Jesse, confirmed create-quip-app@0.1.1, adding the pack option did the trick. One thing that was frustrating was that I had to sign out of my Quip session and sign back in before the app would show up.

**Comment by jesseditson** [comment]
Awesome, glad to hear it! I'll make a note of the sign in issue and see if we can repro on our end, thanks!
