### ISSUE TITLE
quip-cli login site mismatch

### ISSUE THREAD

**Issue by gaspar09** [quip/quip-apps#171]
Issues with various login commands

`$ qla login`
Errors on browser because the initial request goes to `https://quip.com` and I am not properly redirected to `https://corp.quip.com`. The google auth fails to authorize me. 

This is resolved by setting the `site` flag

`$ qla login --site=corp.quip.com` 
Errors because the site argument is used to derive the platform endpoint as `platform-${site}`. 
The request (`https://platform-corp.quip.com`) results in a not found error on the terminal.

**Comment by gaspar09** [comment]
cc @jesseditson

**Comment by jesseditson** [comment]
I see the error when using --site=corp.quip.com, but the idea is that if you're not on a VPC, you should be able to just use quip.com. I get redirected just fine, maybe this doesn't work if you're logged in to multiple quip sites?

**Comment by jesseditson** [comment]
I also just tested a fresh login via CLI and it redirects me properly as well.

**Comment by gaspar09** [comment]
That's probably it, I do have a multi-account and its sending the login flow to the email for one of those.
