### ISSUE TITLE
Error: Invalid Bundle md5 is a required field. Publishing failed. While I am trying to publish the Quip custom live to dev console using qla publish

### ISSUE THREAD

**Issue by rajkumar-react1720** [quip/quip-apps#175]
Error: Invalid Bundle md5 is a required field. Publishing failed. While I am trying to publish the Quip custom live to dev console using qla publish

**Comment by rajkumar-react1720** [comment]
cc @jesseditson

**Comment by jesseditson** [comment]
Hey there! We have not yet enabled quip-cli access for the general public, but I'll follow up here once we do! If you're using this internally at Salesforce, use `npm install -g quip-cli@next` to get the version of the tool that tracks the latest APIs! Thanks for your patience, we'll be shipping new documentation and console changes and enabling `quip-cli` online tools for everyone soon!

**Comment by rajkumar-react1720** [comment]
@jesseditson Thank you so much for your response. I am working on developing the custom live app for an Organization. I tried the command you provided and published successfully.

Thank you.!!

**Comment by jesseditson** [comment]
Awesome, great to hear! Let us know if you run into other issues!
