### ISSUE TITLE
quip developer console broken

### ISSUE THREAD

**Issue by DavidWiener84** [quip/quip-apps#18]
1) Removing and updating our app is throwing a 403
![screen shot 2018-08-03 at 12 55 18 am](https://user-images.githubusercontent.com/1209503/43631568-5fc02af4-96b8-11e8-94c6-26a2ca6a6bfd.png)

2) We are getting manifest errors. When we upload the new .ele file, it is saying that the manifest ID doesn’t match (but it definitely does match). We get this same error when we download the existing ele, bump the version, and re-upload the exact same ele. So something about the ele upload validation seems to be awry.

3) SSL/cert issue on the quip dev console. This has been going on for the last couple days, but seems to be happening with certain servers. When we access it from the US, we don’t get this issue, but when our remote dev team (outside the US) tries, they hit the cert issue. Something worth looking at
![screen shot 2018-08-03 at 12 54 36 am](https://user-images.githubusercontent.com/1209503/43631468-206fadca-96b8-11e8-9adc-f3af983fd4d3.png)

**Comment by elsigh** [comment]
These should be fixed now, please re-open if not the case
