### ISSUE TITLE
cannot publish a freshly made app to a non-quip.com site

### ISSUE THREAD

**Issue by jdoconnor** [quip/quip-apps#181]
using `next` version as of 2021-02-26 on a windows 10 dev vm

after making an app with `qla init -s <somesite>`, trying to `qla publish -s <somesite>` indicates success on the command line, but the live app doesn't have a version associated with it on the /dev/console

**Comment by jesseditson** [comment]
Curious: do you see the app in a corp.quip.com? Maybe it isn't picking up the -s flag properly

**Comment by jdoconnor** [comment]
the init worked, so it should have failed an id check on publish if going to the wrong site

**Comment by jesseditson** [comment]
I'm not sure that's the most deterministic way to test this. Can you check https://quip.com/dev/console to see if it's creating apps there just to humor me? I'll also try to set this up on a new quip site so I can repro.

**Comment by jesseditson** [comment]
Resolved in https://github.com/quip/quip-apps/pull/184
