### ISSUE TITLE
qli init failed to switch to the newly created directory before running `npm install`

### ISSUE THREAD

**Issue by jdoconnor** [quip/quip-apps#182]
using next as of 2021-02-26 on a windows dev VM

After running init, the `npm install` failed, because it was run at the directory where init was run instead of the newly created directory.

**Comment by jesseditson** [comment]
After investigating, I think this isn't due to the directory but instead due to the fact that when invoking npm as a child process windows wants you to use `npm.cmd` not `npm`. (I tested and verified this hypothesis locally)
