### ISSUE TITLE
BUG: Salesforce Record App doesn't decode ' characters accurately

### ISSUE THREAD

**Issue by geoffrothman** [quip/quip-apps#19]
When the app writes to Salesforce, it decodes the ' character fine as evidenced in this image:
![image](https://user-images.githubusercontent.com/4984045/43663489-4a4086b6-972f-11e8-853f-44f0b5338901.png)

But when Quip shows the refreshed data, it doesn't decode the ' character accurately as seen here:
![image](https://user-images.githubusercontent.com/4984045/43663346-bf48a4c6-972e-11e8-9a72-979ec07c83d3.png)

**Comment by geoffrothman** [comment]
@elsigh I think the fix is to add another escape for &#39; as I've done in the 2 bolded new lines of code below:

export function unescapeHTML(str) {
    str = String(str);
    const HTML_UNESCAPE_AMP_RE_ = /\&amp;/g;
    const HTML_UNESCAPE_LT_RE_ = /\&lt;/g;
    const HTML_UNESCAPE_GT_RE_ = /\&gt;/g;
    **const HTML_UNESCAPE_APO_RE_ = /\&#39;/g;**
    if (!str || str.indexOf("&") == -1) {
        return str;
    }
    str = str.replace(HTML_UNESCAPE_LT_RE_, "<");
    str = str.replace(HTML_UNESCAPE_GT_RE_, ">");
    str = str.replace(HTML_UNESCAPE_AMP_RE_, "&");
    **str = str.replace(HTML_UNESCAPE_AMP_RE_, "'");**
    return str;
}

**Comment by elsigh** [comment]
@rafaelweinstein ^^

**Comment by rafaelweinstein** [comment]
cc @sudowork. I noticed this as well. The data is coming from the UI API HTML-escape encoded.

**Comment by geoffrothman** [comment]
@elsigh @rafaelweinstein Another end user negative impact is that it triggers an error message after you click on "Save to Salesforce" which is misleading because it really does save. As a result of the error handling, it leaves the field value that was saved in "Draft" mode with the green flag. Hopefully this is a quick fix? I can't teach all of our Sales Reps and Sales Engineers how to do this until that time because it'll confuse them. tks! Here's the pic: https://www.screencast.com/t/MKtSnN5H

**Comment by geoffrothman** [comment]
@sudowork @elsigh Here's a diff file with the changes that might fix it: 
[geoffdiff.txt](https://github.com/quip/quip-apps/files/2626473/geoffdiff.txt)
