### ISSUE TITLE
Permit ordering with drag n drop cells between columns or cells 

### ISSUE THREAD

**Issue by fredygamez** [quip/quip-apps#2]
Amazing new feature from Quip. However, it would be handy  to have "Trello Style" cards allowing drag and drop cells freely. Currently only I can move columns.  Thanks.

**Comment by elsigh** [comment]
Where are you seeing this? Can you describe how you repro'd? In kanbans, you should be able to move the cards _and_ the columns. Thanks!

**Comment by drewhamlin** [comment]
Try dragging the cards from the space around the edge or at the bottom rather than on the text.

**Comment by fredygamez** [comment]
OK, got it. It works with the bottom edge when it appears a "hand" to drag n drop. Thanks Quip team.
