### ISSUE TITLE
There's no way to save changes on the Quip Mobile App for the Salesforce Record widget

### ISSUE THREAD

**Issue by geoffrothman** [quip/quip-apps#21]
On the desktop, I can click on the "Save to Salesforce" option but in the mobile app, I tap the custom object gray icon "Specialist Forecast" on the quip mobile app but nothing happens. It shows a "draft" green option on the mobile app but no save option.

![image](https://user-images.githubusercontent.com/4984045/43787668-224bf55a-9a31-11e8-96ac-cf326ef4a733.png)

**Comment by elsigh** [comment]
I believe this is by design for now

**Comment by geoffrothman** [comment]
> I believe this is by design for now

@elsigh would love for Nate and crew to reconsider this because Quips strong mobile app is the biggest differentiator between companies using OneNote, Evernote etc.
