### ISSUE TITLE
Project Tracker app doesn’t allow you to select an Owner in the Mobile App

### ISSUE THREAD

**Issue by geoffrothman** [quip/quip-apps#22]
I tap on the first line item where my face is so I can add someone else and nothing responds to my touch. 

![d0000018-6368-406c-b67a-dec5e00d81e8](https://user-images.githubusercontent.com/4984045/43838812-06586a5c-9ae2-11e8-8792-96ed258eb76d.png)

**Comment by elsigh** [comment]
added to our internal bug tracking doc. thanks
