### ISSUE TITLE
Project Tracker app returns you to the top of the screen when you try to choose a Status on the mobile app

### ISSUE THREAD

**Issue by geoffrothman** [quip/quip-apps#23]
When selecting a status, I’d like for the menu modal to pop up with my choices and leave the focus of the cursor on the menu vs returning me to the top of the document and leaving the cursor there. This forces me to have to scroll all the way back down just to finish choosing my menu selection on the popup modal.

![57b89c07-efb9-4f4f-ada1-143f22c10d85](https://user-images.githubusercontent.com/4984045/43838909-4dc91d3c-9ae2-11e8-9e99-c63aef9ea97a.png)

**Comment by elsigh** [comment]
Added to our internal bug tracking document, thank you.
