### ISSUE TITLE
Error when including JSON file

### ISSUE THREAD

**Issue by annyhe** [quip/quip-apps#24]
To reproduce:
1. go to any quip live app
2. include package.json in it: `const packageJSON = require("file-loader!../package.json");`
3. reload the app. You'll see the error
<img width="510" alt="screen shot 2018-08-24 at 3 04 13 pm" src="https://user-images.githubusercontent.com/17040750/44610033-3380e200-a7af-11e8-8497-fd8e79059cc1.png">

**Comment by annyhe** [comment]
@elsigh This is the problem we saw today. Looking forward to a resolution.

**Comment by elsigh** [comment]
@annyhe I tested (and both worked) `import foo from "./file.json"` and `require("./file.json")`
