### ISSUE TITLE
Quip App (in dev status) fails to load for user with view perms?

### ISSUE THREAD

**Issue by timothy-law** [quip/quip-apps#29]
Not sure if this is expected behavior or not: I have a Quip App that's in development mode (i.e. not released):
- People who I share the doc with (Share > Add People) can interact with the app
- If I generate a Shareable Link (Share > Get Link ... set view only), user sees "[...app] failed to load" error

Should people with a view only link be able to see the app? 
Is it because the app isn't released yet?

Thanks!

**Comment by elsigh** [comment]
Are they in the same company as you?

**Comment by timothy-law** [comment]
Yup. I think the issue was with that particular user's environment -- tested with some other internal folks and they can view. Will close issue now.
