### ISSUE TITLE
Feature Request: integrate Project Tracker App with new Tasks tracking capability

### ISSUE THREAD

**Issue by geoffrothman** [quip/quip-apps#35]
When the owner and deadline fields are completed in any project tracker row, also automatically create a Task with owner and due date as shown here and keep the two in sync:

![image](https://user-images.githubusercontent.com/4984045/52365055-30e81100-2a0c-11e9-9472-aab17252d280.png)

**Comment by elsigh** [comment]
We're not using this repo to take feature requests for LiveApps =)
