### ISSUE TITLE
Support for unsafe eval option

### ISSUE THREAD

**Issue by amjha** [quip/quip-apps#37]
I am trying to build a graphic calculator app using [Desmos](https://www.desmos.com/api/v1.1/docs/index.html). When I load the app in my document it throws this error in browser console :

> EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src https://quip-cdn.com 'self'"

I tried adding `'unsafe-eval'` option in script_srcs in csp_sources but it fails when I try to upload app.ale file into the app console with error:
> The package has an invalid value for script_srcs:

Some of the options I tried in manifest file is listed [here](https://salesforce.stackexchange.com/questions/253047/adding-self-unsafe-inline-and-unsafe-eval-in-manifest-file-of-quip-live-a).

Does quip liveapps not support the `unsafe-eval`? How can I incorporate `unsafe-eval` option to execute Desmos JS script in my live app.

**Comment by elsigh** [comment]
We can enable `unsafe-eval` on a case-by-case basis. Feel free to contact me on Quip and I'll help you out - I'm lindsey@quip.com
