### ISSUE TITLE
Live Apps not loading : "Found undesirable cookie" error

### ISSUE THREAD

**Issue by shreyap83** [quip/quip-apps#374]
There is an issue will all live apps not loading in the quip document when viewed on the browser.  ![image](https://user-images.githubusercontent.com/95650626/157503512-b0e2823a-2194-4c0c-923e-ac3a19568a57.png)

**Comment by rgolding** [comment]
This issue has now been resolved, there are still undesirable cookie logs but the live apps should load. We will work on false error logs asap. @shreyap83 please re-open if you have any trouble loading a live app.
