### ISSUE TITLE
Unable to show Icons

### ISSUE THREAD

**Issue by ramsabarish** [quip/quip-apps#38]
I've successfully installed & imported the SLDS React in Quip Live App. I'm able to use most of the  SLDS React components, like Spinner, Card, Button and so on. Unfortunately, I'm failing to display Icons. 

I've tried to display the icons using the IconSettings class, the svg is added to the DOM but not getting displayed.

**App.jsx**
//Import App css 
import "./App.css";
import Styles from "./App.less";

//import SLDS CSS Libraries
import "@salesforce-ux/design-system/assets/styles/salesforce-lightning-design-system.min.css";
import "./dsr-quip-mods.css";

//Import SLDS Components 
import {Card, IconSettings, Icon, Input, Datepicker} from "@salesforce/design-system-react";
import UtilitySprite from "@salesforce-ux/design-system/assets/icons/utility-sprite/svg/symbols.svg";

export default class App extends React.Component {
	
		
    render() {
        return <IconSettings iconPath="/assets/icons">
		 <div>
		  
		  
		  <div>Hello</div>
		  <div style={{background: "aliceblue"}}>
		  <Icon
							assistiveText={{ label: 'Announcement' }}
							category="utility"
							name="add"
							size="small"
						/></div>
		 </div>	
		 </IconSettings>;
    }
}  

Please refer the attached screenshot to view the output.
![Icons-Issue](https://user-images.githubusercontent.com/10074524/54073875-2f7f6200-42b2-11e9-9871-bc2b68218287.png)

Kindly help me out, I'm stuck with this issue for a very long time.

**Comment by elsigh** [comment]
Check out the example for how we did this in the Einstein Analytics Live App - https://github.com/quip/quip-apps/blob/master/examples/einstein-analytics/src/App.jsx#L465 

You need to implement `IconSettings` like so:
```
<IconSettings
            onRequestIconPath={({category, name}) => `#${name}`}>```
