### ISSUE TITLE
How to create a new Quip live app

### ISSUE THREAD

**Issue by keerthikambhampati9** [quip/quip-apps#39]
I'm trying to create a Quip Live App by following this document 
https://finastracomity.quip.com/dev/liveapps/ 
I am stuck at 3rd point 
Run create-quip-app my-app in your terminal. 

"'create-quip-app' is not recognized as an internal or external command,
operable program or batch file."

Then i thought let me do trailhead 
https://trailhead.salesforce.com/content/learn/projects/quick-start-quip-live-apps/set-up-your-quip-live-app-developer-environment 
I'm stuck at "Install the Quip SDK"
 
 Download the Quip SDK zip file. It has a name like quip-apps-sdk-0.91.zip.

This download link is not working from trail head.

Stuck two ways, can you shed some quick light please?

**Comment by jesseditson** [comment]
Make sure you've followed the `prerequisites` section in finastracomity.quip.com/dev/liveapps - Specifically, the docs say to use `npm install -g create-quip-app` before running `create-quip-app`, which seems to be your issue.

**Comment by keerthikambhampati9** [comment]
I got it working in MAC, it wasn't working in Windows. Strange!! thank you
