### ISSUE TITLE
How do I access surrounding thread text from custom liveapp?

### ISSUE THREAD

**Issue by dmvaldman** [quip/quip-apps#40]
Sorry that this is not an "issue", more of a question. 

I'm trying to create a "takeaways" liveapp, which gathers all @mentions in a document and creates a checklist grouped by user. To do this I'd need access to the content of the document, hopefully in a structured way. Navigating through the tutorials, I don't see a way to do this. Any help would be appreciated. Thank you!

**Comment by smangelberg** [comment]
At the current time, the only way to do this would be to have your live app request either domain or user automation API access (https://quip.com/dev/automation/documentation); for security reasons, we prevent a live app from having access to the document itself.
