### ISSUE TITLE
Missing Modal in salesforce-record

### ISSUE THREAD

**Issue by sebas00** [quip/quip-apps#5]
It seems the Modal is missing from the salesforce-record example, resulting the following error on build:

ERROR in ../shared/base-field-builder/field.jsx
Module not found: Error: Can't resolve '../table-view/lib/components/Modal' in '/Users/sdeman/sfrecord/examples/salesforce-record/shared/base-field-builder'

**Comment by spiderjava** [comment]
Same error of user sebas00, during the npm start I receive this error:

ERROR in ../shared/base-field-builder/field.jsx
Module not found: Error: Can't resolve '../react-modal/lib/components/Modal' in '/Users/nguarnacci/Google Drive/Projects/Quip_Apps/custom-record/shared/base-field-builder'
 @ ../shared/base-field-builder/field.jsx 40:13-59
 @ ../shared/base-field-builder/record.jsx
 @ ./src/record-picker.jsx
 @ ./src/root.jsx
 @ multi babel-polyfill ./src/root.jsx

Is it possible to provide stable version fo this example??

**Comment by derindutz** [comment]
Should be fixed with https://github.com/quip/quip-apps/commit/04e876023237e5576297810c03dce38193291cb7! Let us know if you're still running into issues.
