### ISSUE TITLE
Please check 'proxy_api_domains' in your element configuration.

### ISSUE THREAD

**Issue by agneet42** [quip/quip-apps#62]
When trying to fetch Apex Classes from my developer account, using a connected App, facing this issue :  

https://ap16.salesforce.com/services/data/v43.0/query/?q=SELECT%20Id%2C%20Name%20FROM%20ApexClass' doesn't match any whitelisted domains. Please check 'proxy_api_domains' in your element configuration.

**Comment by jesseditson** [comment]
Here's the documentation for auth config:

https://quip.com/dev/liveapps/documentation#auth-config

That link has details on what proxy domains are - to use quip auth, you'll need to configure the auth for your live app in your quip console.
