### ISSUE TITLE
"Salesforce List" Live App doesn't decode rich text field values in Quip

### ISSUE THREAD

**Issue by geoffrothman** [quip/quip-apps#82]
This is a *massive* barrier to Enterprise adoption (and probably just as important, internal Salesforce adoption)

Am looking for something like this to happen to fix it:
https://medium.com/@tertiumnon/js-how-to-decode-html-entities-8ea807a140e5

This is probably related to #43 as well

![htmlencode](https://user-images.githubusercontent.com/4984045/84558646-05f58780-acfa-11ea-917c-d1d1db4eac5f.png)

**Comment by jesseditson** [comment]
Hey there! We parse field types marked as html, what is the DataType of this field in Salesforce? A simple rich text field works for me:

![image](https://user-images.githubusercontent.com/370239/84693469-605e3600-aefc-11ea-9072-efd3de0087ff.png)

Here's the Salesforce config:

![image](https://user-images.githubusercontent.com/370239/84693594-97344c00-aefc-11ea-92f6-9203b4357415.png)

I also can point to org62 if you're using this in that context and have a repro there I can look at.

**Comment by geoffrothman** [comment]
Thanks @jesseditson!! They're both a  "Rich Text Area" field and here are the org62 links to them: 

1) Existing Content Links/Info https://org62.lightning.force.com/lightning/setup/ObjectManager/01I30000000GdDe/FieldsAndRelationships/00N3000000ATe82/view
2) Current Status and Next Steps Historyhttps://org62.lightning.force.com/lightning/setup/ObjectManager/01I30000000GdDe/FieldsAndRelationships/00N0M00000CNibX/view

**Comment by geoffrothman** [comment]
@jesseditson YAYYYYY!!! I just tested today and the issue's gone....woohoo....thanks man!!
