### ISSUE TITLE
Custom params to import into Quip App

### ISSUE THREAD

**Issue by DTwigs** [quip/quip-apps#84]
I want to create a custom iframe container that is reusable with different URLS
I was wondering if there is a way to call the same app multiple times but with different params. 
e.g.
@myApp("https://github.com")
@myApp("https://quip.com")

**Comment by jesseditson** [comment]
I'd recommend adding a configuration screen as the first step in your app, then storing the configured parameter in your root record. Users will at-mention your app, then when they insert it, they'll be prompted for the URL, which you can handle however you like.

**Comment by DTwigs** [comment]
Thats a good way to handle it.  I also found out I could use url pattern detection to initiate the app like in your spotify example and that is going to work out well for me.  Thank you.
