### ISSUE TITLE
Quip App loads perfectly when first initializing it, on refresh it fails with "refused to frame..."

### ISSUE THREAD

**Issue by DTwigs** [quip/quip-apps#85]
`Refused to frame 'https://localhost:8888/' because it violates the following Content Security Policy directive: "frame-src [my url]".`

This is the error I'm getting in console. I'm not sure what differs when reloading the quip document vs initializing the quip live app for the first time.  

My app detects a certain url pattern and once you initialize the app on that URL it puts the url into an iframe and inserts it into the quip doc.  (the url im loading into the iframe is not localhost:8888 that just my quip live app location)

root.jsx:
```
quip.apps.initialize({
    initializationCallback: function(root, params) {
        var height = "520px";
        root.innerHTML =
            '<iframe width="' +
            quip.apps.getContainerWidth() +
            'px" height="' +
            height +
            '" src="' +
            params.creationUrl +
            '" frameborder="0" allowtransparency="true"></iframe>';
        var iframe = root.firstChild;
        quip.apps.registerEmbeddedIframe(iframe);
    },
});
```

manifest:
```
{
    [...]
    "sizing_mode": "fit_content",
    "initial_height": 300,
    "initial_width": 300,
    "js_files": ["dist/app.js"],
    "css_files": ["dist/app.css"],
    "csp_sources": {
        "frame_srcs": ["http://www.google.com"]
    },
    "intercept_url_patterns": [
        "http://www.google.com"
    ]
}
```
google.com is just an example, but i would be trying to load something like `http://www.google.com/embed/5/dAWIOdi` into an iframe.

Do you guys have any thoughts on why this is happening?

**Comment by jesseditson** [comment]
it looks like your csp sources are configured correctly, but the manifest is not dynamically pulled from the file, so you should verify that you can see the right csp_sources field in `https://quip.com/dev/console` - generally, if your app manifest changes, you'll need to upload a new `app.ele` file and reload the page for us to pick up the changes.

**Comment by DTwigs** [comment]
Yes, I can view the manifest file in the quip dev console and it has the right values.  And it works when initializing the quip live app, but it errors out when reloading the quip doc.

**Comment by DTwigs** [comment]
I discovered the solution to my issue.  The problem is that the params.creationUrl does note exist on subsequent reloads of the page.  So I ended up storing the creationUrl in the rootrecord to fetch later.

**Comment by jesseditson** [comment]
Ah that makes sense - I'll keep that in mind when writing new docs and updating the API, it does seem worth explicitly mentioning or changing. Thanks for following up!
